version: "2.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_URI: "mysql+pymysql://root:123456@mysql:3306/sso"
    ports:
      - "80:80"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:latest
    healthcheck:
      test: mysqladmin ping -h mysql -u root -p123456
      interval: 30s
      timeout: 5s
      retries: 5
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "sso"
